name: My First Github Action
on: [push]
jobs:
 print-hello-world:
   runs-on: ubuntu-latest
   steps:
    - run: echo 'Hello World!!'
 print-hello-world2:
   runs-on: ubuntu-latest
   steps:
    - run: echo 'Hello World!!'
     